/** This file is automatically generated by webpack plugins, no not edit
 *
 * In server.ts, import this file
 * import { Imports, RegisterFunction } from "./server_types";
 */

import { webserver } from "../webserver/server_exports";
export * from "../webserver/server_exports";

export interface Imports
{
	webserver: webserver;
}


export interface Exports
{
}

export type RegisterFunction = (error: null | Error, provides: Exports) => void;
