/** This file is automatically generated by webpack plugins, no not edit
 *
 * In ui.ts, import this file
 * import { Imports, RegisterFunction } from "./ui_types";
 */

import { application } from "./ui_exports";
export * from "./ui_exports";

export interface Imports
{
}


export interface Exports
{
	application: application;
}

export type RegisterFunction = (error: null | Error, provides: Exports) => void;

declare global
{
	export interface UI
	{
		application: application;
	}
}

