/** This file is automatically generated by webpack plugins, no not edit
 *
 * In ui/ui.ts, import this file
 * import { Imports, RegisterFunction } from "./ui_types";
 */

import { application } from "../../application/ui_exports";
export * from "../../application/ui_exports";
import { workspace } from "../../workspace/ui_exports";
export * from "../../workspace/ui_exports";
import { image_display } from "./ui_exports";
export * from "./ui_exports";

export interface Imports
{
	application: application;
	workspace: workspace;
}


export interface Exports
{
	image_display: image_display;
}

export type RegisterFunction = (error: null | Error, provides: Exports) => void;

declare global
{
	export interface UI
	{
		image_display: image_display;
	}
}

